name: trdeploy

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    name: build
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: printf 'TERRAGRUNT_CONFIG_NAME=terragrunt.hcl\nTERRAFORM_DIR=.terraform\nCONFIG_FILE_NAME=trdeploy' > .env && make build
    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "cmd/trdeploy"
        tags: true
        draft: false
